# Generated by Django 2.2.13 on 2020-07-21 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0006_auto_20190820_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='countryhealth',
            name='total_funding',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
