# Generated by Django 2.2.13 on 2020-07-21 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0007_countryhealth_total_funding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countryhealth',
            name='total_funding',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
    ]
