# Generated by Django 2.2.13 on 2020-07-23 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0008_auto_20200721_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='countryhealth',
            name='hiv_incidence',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
    ]
