# Generated by Django 2.2.13 on 2020-07-23 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0009_countryhealth_hiv_incidence'),
    ]

    operations = [
        migrations.RenameField(
            model_name='countryhealth',
            old_name='hiv_incidence',
            new_name='hiv_incidence2018',
        ),
    ]
