# Generated by Django 2.2.13 on 2020-07-23 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0010_auto_20200723_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='countryhealth',
            name='household',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
    ]
