# Generated by Django 2.2.13 on 2020-07-23 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0011_countryhealth_household'),
    ]

    operations = [
        migrations.AddField(
            model_name='countryhealth',
            name='all_tb_incidence2018',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
    ]
