# Generated by Django 2.2.13 on 2020-07-24 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0013_auto_20200724_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='countrydetail',
            name='world_bank_gdp',
            field=models.FloatField(blank=True, help_text='GDP (current US$)', null=True),
        ),
        migrations.AlterField(
            model_name='countryhealth',
            name='pop_dens',
            field=models.CharField(blank=True, help_text='Population density (people per sq. km of land area', max_length=36, null=True),
        ),
    ]
