# Generated by Django 2.2.13 on 2020-07-27 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0016_auto_20200727_0944'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='countrydetail',
            name='world_bank_gdp',
        ),
        migrations.AddField(
            model_name='countryhealth',
            name='world_bank_gdp',
            field=models.CharField(blank=True, help_text='GDP (current US$)', max_length=36, null=True),
        ),
    ]
