# Generated by Django 2.2.13 on 2020-07-27 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0017_auto_20200727_1045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='countryhealth',
            name='world_bank_gdp',
        ),
        migrations.AddField(
            model_name='countryhealth',
            name='total_wealth',
            field=models.CharField(blank=True, help_text='Total wealth per capita (constant 2014 US$)', max_length=36, null=True),
        ),
    ]
