# Generated by Django 2.2.13 on 2020-07-27 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0018_auto_20200727_1639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='countryhealth',
            name='est_mdr',
        ),
    ]
