# Generated by Django 2.2.13 on 2020-07-27 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0019_remove_countryhealth_est_mdr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='countryhealth',
            name='pop_dens',
        ),
    ]
