# Generated by Django 2.2.13 on 2020-07-27 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0020_remove_countryhealth_pop_dens'),
    ]

    operations = [
        migrations.AddField(
            model_name='countryhealth',
            name='est_mdr',
            field=models.FloatField(blank=True, help_text='Estimated % Drug Resistance for the country', null=True),
        ),
        migrations.AddField(
            model_name='countryhealth',
            name='pop_dens',
            field=models.CharField(blank=True, help_text='Population density (people per sq. km of land area', max_length=36, null=True),
        ),
        migrations.AddField(
            model_name='countryhealth',
            name='world_bank_gdp',
            field=models.CharField(blank=True, help_text='GDP (current US$)', max_length=36, null=True),
        ),
    ]
