#!/bin/bash
#
# Provides a help script to call manage.py with local virtualenv
#

# Move us to the script directory (should be the root)
cd "$( dirname "$0" )"

for filename in */bin/activate; do
  if [ -f "$filename" ]; then
    # Doesn't matter if it's pythonenv, venv or something else
    source */bin/activate

    # Set the settings to a special management PY file.
    export DJANGO_SETTINGS_MODULE=tb_website.settings.manage

    # Run the manage.py in the current directry
    ./manage.py $@

    # Exit with the same exit status
    exit $?
  fi
done

echo "No virtualenv (python virtual environment) found in $PWD."
exit 2

