# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-03 15:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tb_users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tbuser', to=settings.AUTH_USER_MODEL),
        ),
    ]
