# Generated by Django 2.0.13 on 2019-08-20 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tb_users', '0002_auto_20190603_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbuser',
            name='md5',
            field=models.CharField(blank=True, db_index=True, help_text='auto-filled on save', max_length=40),
        ),
    ]
