# Generated by Django 2.0.13 on 2019-08-20 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exploredatafileinfo',
            name='active',
            field=models.BooleanField(default=True, help_text='The *most recently created* active entry will be used'),
        ),
        migrations.AlterField(
            model_name='exploredatafileinfo',
            name='codebook_file_url',
            field=models.URLField(help_text='Example: https://dataverse.harvard.edu/api/access/datafile/2694344'),
        ),
        migrations.AlterField(
            model_name='exploredatafileinfo',
            name='name',
            field=models.CharField(help_text='For internal use', max_length=255),
        ),
        migrations.AlterField(
            model_name='exploredatafileinfo',
            name='two_ravens_url',
            field=models.URLField(help_text='Example: https://rserve.dataverse.harvard.edu/dataexplore/gui.html?dfId=2693726&key=c54f07b7-5098-461c-adf3-a976c0d62f6e'),
        ),
    ]
