#!/usr/bin/env python
"""
A fake bsub command for local use and testing.
"""

import os
import sys

from subprocess import call
from argparse import ArgumentParser

def main():
    """Main function"""
    parser = ArgumentParser()
    parser.add_argument('-q', '--queue', help="The queue it would have gone.")
    parser.add_argument('-W', '--limit', help="The run limit setting.")
    parser.add_argument('-o', '--stdout', help="filename for the stdout.")
    parser.add_argument('-J', '--job_spec', help="Job identification name")
    parser.add_argument("script", help="The command the bsub would have run.")

    args = parser.parse_args()

    print "Running " + args.script

    stdout = sys.stdout
    stderr = sys.stderr
    if args.stdout:
        stdout = open(args.stdout, 'w')
        stderr = stdout

    # shell=True allows our script to run anything, this a known security allowence
    call(args.script, stdout=stdout, stderr=stderr, shell=True)

if __name__ == '__main__':
    main()

