# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-01-25 20:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0011_remove_predictdataset_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predictpipeline',
            name='pipeline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predicts', to='pipeline.Pipeline'),
        ),
    ]
