# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-31 19:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0012_auto_20190125_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictdataset',
            name='has_notified',
            field=models.BooleanField(default=False, help_text=b'Has this predict messaged the user about the status of their jobs.'),
        ),
    ]
