# Generated by Django 2.0.13 on 2019-08-20 15:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0013_predictdataset_has_notified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predictdataset',
            name='delete_sources',
            field=models.BooleanField(default=False, help_text='If this is checked, we will delete all your input files downloaded from dropbox after running the predict.'),
        ),
        migrations.AlterField(
            model_name='predictdataset',
            name='description',
            field=models.TextField(verbose_name='Dataset description'),
        ),
        migrations.AlterField(
            model_name='predictdataset',
            name='file_type',
            field=models.CharField(choices=[('vcf', 'Variant Call Format (VCF)'), ('fastq', 'FastQ Single Ended Nucleotide Sequence'), ('fastq-pair', 'FastQ Pair Ended Nucleotide Sequences'), ('manual', 'Mutations Manual Entry')], max_length=25),
        ),
        migrations.AlterField(
            model_name='predictdataset',
            name='has_notified',
            field=models.BooleanField(default=False, help_text='Has this predict messaged the user about the status of their jobs.'),
        ),
        migrations.AlterField(
            model_name='predictdataset',
            name='md5',
            field=models.CharField(blank=True, db_index=True, help_text='auto-filled on save', max_length=40),
        ),
        migrations.AlterField(
            model_name='predictdataset',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Dataset Title'),
        ),
        migrations.AlterField(
            model_name='predictdataset',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='datasets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='predictpipeline',
            name='file_type',
            field=models.CharField(choices=[('vcf', 'Variant Call Format (VCF)'), ('fastq', 'FastQ Single Ended Nucleotide Sequence'), ('fastq-pair', 'FastQ Pair Ended Nucleotide Sequences'), ('manual', 'Mutations Manual Entry')], max_length=25),
        ),
        migrations.AlterField(
            model_name='predictpipeline',
            name='pipeline',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='predicts', to='pipeline.Pipeline'),
        ),
        migrations.AlterField(
            model_name='predictstrain',
            name='pipeline',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pipeline.Pipeline'),
        ),
    ]
