# Generated by Django 2.2.13 on 2021-04-15 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0015_predictresult_predictresultlocus'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictpipeline',
            name='is_retired',
            field=models.BooleanField(default=False),
        ),
    ]
