# Generated by Django 2.2.13 on 2021-05-16 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0016_predictpipeline_is_retired'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictresult',
            name='error',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
