# Generated by Django 2.2.13 on 2022-01-24 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0018_predictresult_prediction'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictdataset',
            name='status',
            field=models.TextField(choices=[('FILE_NONE', 'No Files Uploaded'), ('FILE_WAIT', 'Dataset Confirmed'), ('FILE_START', 'File Retrieval Started'), ('FILE_ERROR', 'File Retrieval Failed'), ('RUN_NONE', 'No Strains to process'), ('RUN_WAIT', 'File Retrieval Success'), ('RUN_START', 'Processing Started'), ('RUN_ERROR', 'Processing Failed'), ('RUN_DONE', 'Processing Success'), ('READY', 'Prediction Ready'), ('INVALID', 'Lacks Quality'), ('TIMEOUT', 'Processing Timed Out')], default='', max_length=32, verbose_name='Status'),
        ),
    ]
