# Generated by Django 2.2.13 on 2022-01-24 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0019_predictdataset_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictdataset',
            name='has_lineages',
            field=models.BooleanField(default=False, verbose_name='Has lineages'),
        ),
        migrations.AddField(
            model_name='predictdataset',
            name='has_output_files',
            field=models.BooleanField(default=False, verbose_name='Has any output files'),
        ),
        migrations.AddField(
            model_name='predictdataset',
            name='has_prediction',
            field=models.BooleanField(default=False, verbose_name='Has prediction'),
        ),
        migrations.AlterField(
            model_name='predictdataset',
            name='status',
            field=models.TextField(choices=[('FILE_NONE', 'No Files Uploaded'), ('FILE_WAIT', 'Dataset Confirmed'), ('FILE_START', 'File Retrieval Started'), ('FILE_ERROR', 'File Retrieval Failed'), ('RUN_NONE', 'No Strains to process'), ('RUN_WAIT', 'File Retrieval Success'), ('RUN_START', 'Processing Started'), ('RUN_ERROR', 'Processing Failed'), ('RUN_DONE', 'Processing Success'), ('READY', 'Prediction Ready'), ('INVALID', 'Lacks Quality'), ('TIMEOUT', 'Processing Timed Out'), ('', 'Status Unknown')], default='', max_length=32, verbose_name='Status'),
        ),
    ]
