# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-06-07 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0005_remove_program_requirements'),
    ]

    operations = [
        migrations.AddField(
            model_name='programrun',
            name='follower_id',
            field=models.SlugField(blank=True, help_text=b'Name or ID of the next job that depends on this', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='programrun',
            name='previous_id',
            field=models.SlugField(blank=True, help_text=b'Name or ID of the previous job we depend on', max_length=255, null=True),
        ),
    ]
