# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-09-07 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0006_auto_20180607_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipelinerun',
            name='run_as_test',
            field=models.PositiveIntegerField(blank=True, help_text=b'Every (x) days, run this pipeline-run as a test.', null=True),
        ),
    ]
