# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-10-24 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0007_pipelinerun_run_as_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipelinerun',
            name='clean_files',
            field=models.TextField(blank=True, help_text=b'List of extra files to remove when job is finished', null=True),
        ),
    ]
