# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-03-29 19:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0008_pipelinerun_clean_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='limit',
            field=models.CharField(blank=True, help_text=b'Specify amount of time to limit this process, [days]-[hours]:[minutes]:[seconds]', max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='memory',
            field=models.CharField(choices=[(b'500M', b'500MB'), (b'1M', b'1GB'), (b'2G', b'2GB'), (b'5G', b'5GB'), (b'10G', b'10GB'), (b'20G', b'20GB'), (b'50G', b'50GB'), (b'100G', b'100GB')], default=b'1000M', help_text=b'Amount of memory to request', max_length=16),
        ),
        migrations.AddField(
            model_name='program',
            name='threads',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
