# Generated by Django 2.2.13 on 2020-11-09 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0011_auto_20190820_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='keep_for',
            field=models.IntegerField(choices=[(-1, 'Keep Forever'), (0, 'Do not Keep'), (1, 'Keep for One Hour'), (24, 'Keep for One Day'), (168, 'Keep for One Week'), (744, 'Keep for One Month'), (8760, 'Keep for One Year')], default=-1),
        ),
        migrations.AlterField(
            model_name='program',
            name='keep',
            field=models.BooleanField(default=True, help_text='Should the output files be kept or deleted when the pipeline finishes.'),
        ),
    ]
