# Generated by Django 2.2.13 on 2020-11-09 17:54

from django.db import migrations

def keep_to_for(apps, schema_editor):
    Program = apps.get_model("pipeline", "Program")
    for program in Program.objects.all():
        if program.keep:
            program.keep_for = -1
        else:
            program.keep_for = 168
        program.save()

def for_to_keep(apps, schema_editor):
    Program = apps.get_model("pipeline", "Program")
    for program in Program.objects.all():
        program.keep = program.keep_for == -1
        program.save()

class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0012_auto_20201109_1254'),
    ]

    operations = [
        migrations.RunPython(keep_to_for, for_to_keep),
    ]
