# Generated by Django 2.2.13 on 2020-11-09 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0013_auto_20201109_1254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='keep',
        ),
    ]
