# Generated by Django 2.2.13 on 2020-12-28 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0015_programrun_job_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='quality_control',
            field=models.BooleanField(default=False, help_text='If true, failure in this step is considered a failure of the data, and not failure of the pipeline program.'),
        ),
        migrations.AlterField(
            model_name='programrun',
            name='job_state',
            field=models.CharField(blank=True, choices=[(None, 'Status not requested'), ('', 'Unknown State (non returned)'), ('OUT_OF_MEMORY', 'Out of Memory'), ('TIMEOUT', 'Timeout'), ('CANCELLED', 'Cancelled'), ('FAILED', 'Failed'), ('INVALID', 'Quality Control Failure'), ('COMPLETED', 'Completed')], db_index=True, max_length=16, null=True),
        ),
    ]
