# Generated by Django 2.2.13 on 2021-03-10 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0016_auto_20201228_0927'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipeline',
            name='disabled',
            field=models.BooleanField(default=False, help_text='Automatically disabled pipelines when they have serious syntax errors.'),
        ),
    ]
