# Generated by Django 2.2.13 on 2021-08-30 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0017_pipeline_disabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='command_line',
            field=models.TextField(help_text="\nWrite the command line using replacement syntax for inputs and outputs.\n\n ${file}.in means we expect a file called *.txt with the id 'file'\n @{file}.out means this pipeline will output a file called *.txt using the\n             filename of the input with the id 'file'. For example if the input\n             has the name 'blueberry.in' the output will be 'blueberry.out'\n\n ${bin}program.py means reference the script 'program.py' in the bin folder. These\n            folders are configured by the website admin and there may be multiple\n            directories where scripts are held for your gentb website.\n\n"),
        ),
    ]
