# Generated by Django 2.2.13 on 2021-10-18 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0018_auto_20210830_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='last_edited',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='version',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='programrun',
            name='version',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
