#!/usr/bin/env python
"""
A fake bsub command for local use and testing.
"""

from argparse import ArgumentParser

def main():
    """Main function"""
    parser = ArgumentParser()
    parser.add_argument('-q', '--queue', help="The queue it would have gone.")
    parser.add_argument('-W', '--limit', help="The run limit setting.")
    parser.add_argument('-o', '--stdout', help="filename for the stdout.")
    parser.add_argument('-J', '--job_spec', help="Job identification name")
    parser.add_argument("script", help="The command the bsub would have run.")

    args = parser.parse_args()

    print "Running " + args.script

if __name__ == '__main__':
    main()

