# Generated by Django 2.2.13 on 2021-08-23 16:24

import apps.maptables.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mutations', '0025_auto_20210823_1224'),
        ('maps', '0007_auto_20201123_0957'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=16)),
                ('name', models.CharField(max_length=32)),
                ('description', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='MapRow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField(help_text='The content for this row, must be a json encoded row', validators=[apps.maptables.models.validate_json])),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_map_rows', to='maps.Country')),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_map_rows', to='mutations.Drug')),
                ('parent_map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='maptables.CustomMap')),
            ],
            options={
                'ordering': ('country', 'drug'),
                'unique_together': {('parent_map', 'country', 'drug')},
            },
        ),
    ]
