# Generated by Django 2.2.13 on 2021-08-30 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maptables', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='custommap',
            name='fill_colors',
            field=models.TextField(default='#FFFFDD,#C7E9B4,#7FCDBB,#41B6C4,#1D91C0', help_text='A comma seperated list of colours which the ranges relate to.', max_length=255),
        ),
        migrations.AddField(
            model_name='custommap',
            name='fill_column',
            field=models.CharField(default='count', help_text='The value used to decide what color the fill should be.', max_length=48),
        ),
        migrations.AddField(
            model_name='custommap',
            name='fill_max',
            field=models.DecimalField(decimal_places=4, default=1.0, help_text='The maximum value this field will be.', max_digits=20),
        ),
        migrations.AddField(
            model_name='custommap',
            name='fill_ranges',
            field=models.TextField(default='1/8,1/4,1/2,3/4', help_text='A comma seperated list of color ranges.', max_length=255),
        ),
        migrations.CreateModel(
            name='MapDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=128)),
                ('column', models.CharField(help_text="The column who's value is shown in this detail row.", max_length=48)),
                ('kind', models.CharField(choices=[('str', 'Text String'), ('float', 'Decimal Number'), ('int', 'Integer Number')], default='str', max_length=16)),
                ('parent_map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='maptables.CustomMap')),
            ],
        ),
        migrations.CreateModel(
            name='MapDataFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=128)),
                ('column', models.CharField(max_length=48)),
                ('options', models.TextField(help_text='A json formatted definition of the map filter options')),
                ('parent_map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_filters', to='maptables.CustomMap')),
            ],
        ),
    ]
