# Generated by Django 2.2.13 on 2021-09-06 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maptables', '0002_auto_20210830_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapdatafilter',
            name='key',
            field=models.SlugField(default='', max_length=16),
        ),
        migrations.AddField(
            model_name='mapdatafilter',
            name='kind',
            field=models.CharField(choices=[('limit', 'Limit by values')], default='', max_length=16),
        ),
    ]
