# Generated by Django 2.2.13 on 2021-09-13 15:30

import apps.maptables.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mutations', '0025_auto_20210823_1224'),
        ('maps', '0007_auto_20201123_0957'),
        ('maptables', '0003_auto_20210906_1604'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapDataRow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField(help_text='The content for this row, must be a json encoded row', validators=[apps.maptables.models.validate_json])),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_map_rows', to='maps.Country')),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_map_rows', to='mutations.Drug')),
            ],
            options={
                'ordering': ('country', 'drug'),
            },
        ),
        migrations.CreateModel(
            name='MapDataSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=16)),
                ('name', models.CharField(max_length=48)),
                ('description', models.CharField(blank=True, max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MapDisplay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=16)),
                ('name', models.CharField(max_length=32)),
                ('description', models.CharField(blank=True, max_length=128, null=True)),
                ('fill_column', models.CharField(default='count', help_text='The value used to decide what color the fill should be.', max_length=48)),
                ('fill_max', models.DecimalField(decimal_places=4, default=1.0, help_text='The maximum value this field will be.', max_digits=20)),
                ('fill_ranges', models.TextField(default='1/8,1/4,1/2,3/4', help_text='A comma seperated list of color ranges.', max_length=255)),
                ('fill_colors', models.TextField(default='#FFFFDD,#C7E9B4,#7FCDBB,#41B6C4,#1D91C0', help_text='A comma seperated list of colours which the ranges relate to.', max_length=255)),
                ('data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maps', to='maptables.MapDataSource')),
                ('default_drug', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mutations.Drug')),
            ],
        ),
        migrations.CreateModel(
            name='MapDisplayDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=128)),
                ('column', models.CharField(help_text="The column who's value is shown in this detail row.", max_length=48)),
                ('kind', models.CharField(choices=[('str', 'Text String'), ('float', 'Decimal Number'), ('int', 'Integer Number')], default='str', max_length=16)),
                ('parent_map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='maptables.MapDisplay')),
            ],
        ),
        migrations.CreateModel(
            name='MapDisplayFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(default='', max_length=16)),
                ('kind', models.CharField(choices=[('', 'No filter'), ('limit', 'Limit by values')], default='', max_length=16)),
                ('column', models.CharField(max_length=48)),
                ('label', models.CharField(max_length=128)),
                ('options', models.TextField(help_text='A json formatted definition of the map filter options')),
                ('parent_map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_filters', to='maptables.MapDisplay')),
            ],
        ),
        migrations.RemoveField(
            model_name='mapdatafilter',
            name='parent_map',
        ),
        migrations.RemoveField(
            model_name='mapdetail',
            name='parent_map',
        ),
        migrations.AlterUniqueTogether(
            name='maprow',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='maprow',
            name='country',
        ),
        migrations.RemoveField(
            model_name='maprow',
            name='drug',
        ),
        migrations.RemoveField(
            model_name='maprow',
            name='parent_map',
        ),
        migrations.DeleteModel(
            name='CustomMap',
        ),
        migrations.DeleteModel(
            name='MapDataFilter',
        ),
        migrations.DeleteModel(
            name='MapDetail',
        ),
        migrations.DeleteModel(
            name='MapRow',
        ),
        migrations.AddField(
            model_name='mapdatarow',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='maptables.MapDataSource'),
        ),
        migrations.AlterUniqueTogether(
            name='mapdatarow',
            unique_together={('source', 'country', 'drug')},
        ),
    ]
