# Generated by Django 2.2.13 on 2021-09-13 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maptables', '0004_auto_20210913_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapdatasource',
            name='slug',
            field=models.SlugField(max_length=32),
        ),
        migrations.AlterField(
            model_name='mapdisplay',
            name='slug',
            field=models.SlugField(max_length=32),
        ),
        migrations.AlterField(
            model_name='mapdisplayfilter',
            name='key',
            field=models.SlugField(default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='mapdisplayfilter',
            name='kind',
            field=models.CharField(choices=[('', 'No filter'), ('limit', 'Limit by values')], default='', max_length=32),
        ),
    ]
